kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  selfLink: /apis/apps/v1/namespaces/test-project/deployments/redis-secondary
  resourceVersion: '8755487'
  name: redis-secondary
  uid: aedfb8b7-e000-4af6-b19a-4ec39df0915f
  creationTimestamp: '2020-11-09T13:44:45Z'
  generation: 5
  namespace: test-project
  labels:
    app: redis-secondary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-secondary
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-secondary
    spec:
      containers:
        - name: redis-slave
          image: voteva/redis-slave
          ports:
            - name: redis-slave
              containerPort: 6379
              protocol: TCP
          env:
            - name: REDIS_MASTER_SERVICE_HOST
              value: redis-primary
            - name: REDIS_MASTER_SERVICE_PORT
              value: '6379'
            - name: SENTINEL_ANNOUNCE_PORT
              value: '26379'
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
        - name: redis-sentinel
          image: voteva/redis-slave-sentinel
          ports:
            - name: redis-sentinel
              containerPort: 26379
              protocol: TCP
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: MASTER_ANNOUNCE_PORT
              value: '6379'
            - name: SENTINEL_ANNOUNCE_PORT
              value: '26379'
            - name: REDIS_MASTER_SERVICE_HOST
              value: redis-primary
            - name: REDIS_MASTER_SERVICE_PORT
              value: '6379'
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 5
  replicas: 2
  updatedReplicas: 2
  readyReplicas: 2
  availableReplicas: 2
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2020-11-09T13:45:05Z'
      lastTransitionTime: '2020-11-09T13:44:45Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "redis-secondary-57cf4cb949" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2020-11-09T14:16:51Z'
      lastTransitionTime: '2020-11-09T14:16:51Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
