kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis-primary
  labels:
    app: redis-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-primary
  template:
    metadata:
      labels:
        app: redis-primary
    spec:
      containers:
        - name: redis-master
          image: voteva/redis-master
          ports:
            - name: redis-master
              containerPort: 6379
              protocol: TCP
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: MASTER_ANNOUNCE_PORT
              value: '6379'
            - name: SENTINEL_ANNOUNCE_PORT
              value: '26379'
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          imagePullPolicy: Always
        - name: redis-sentinel
          image: voteva/redis-sentinel
          ports:
            - name: redis-sentinel
              containerPort: 26379
              protocol: TCP
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: MASTER_ANNOUNCE_PORT
              value: '6379'
            - name: SENTINEL_ANNOUNCE_PORT
              value: '26379'
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          imagePullPolicy: Always