kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis-secondary
  labels:
    app: redis-secondary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-secondary
  template:
    metadata:
      labels:
        app: redis-secondary
    spec:
      containers:
        - name: redis-slave
          image: voteva/redis-slave
          ports:
            - name: redis-slave
              containerPort: 6379
              protocol: TCP
          env:
            - name: REDIS_MASTER_SERVICE_HOST
              value: redis-primary
            - name: REDIS_MASTER_SERVICE_PORT
              value: '6379'
            - name: SENTINEL_ANNOUNCE_PORT
              value: '26379'
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          imagePullPolicy: Always
        - name: redis-sentinel
          image: voteva/redis-slave-sentinel
          ports:
            - name: redis-sentinel
              containerPort: 26379
              protocol: TCP
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: MASTER_ANNOUNCE_PORT
              value: '6379'
            - name: SENTINEL_ANNOUNCE_PORT
              value: '26379'
            - name: REDIS_MASTER_SERVICE_HOST
              value: redis-primary
            - name: REDIS_MASTER_SERVICE_PORT
              value: '6379'
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          imagePullPolicy: Always