kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
  selfLink: /apis/apps/v1/namespaces/test-project/deployments/redis-primary
  resourceVersion: '8754497'
  name: redis-primary
  uid: 113cf9e1-84e1-4e33-b706-69f5c6eb3be2
  creationTimestamp: '2020-11-09T13:32:38Z'
  generation: 14
  namespace: test-project
  labels:
    app: redis-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-primary
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-primary
    spec:
      containers:
        - name: redis-master
          image: voteva/redis-master
          ports:
            - name: redis-master
              containerPort: 6379
              protocol: TCP
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: MASTER_ANNOUNCE_PORT
              value: '6379'
            - name: SENTINEL_ANNOUNCE_PORT
              value: '26379'
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
        - name: redis-sentinel
          image: voteva/redis-master-sentinel
          ports:
            - name: redis-sentinel
              containerPort: 26379
              protocol: TCP
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: MASTER_ANNOUNCE_PORT
              value: '6379'
            - name: SENTINEL_ANNOUNCE_PORT
              value: '26379'
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 14
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2020-11-09T13:41:36Z'
      lastTransitionTime: '2020-11-09T13:32:38Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "redis-primary-67594b98ff" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2020-11-09T14:14:38Z'
      lastTransitionTime: '2020-11-09T14:14:38Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
