kind: Service
apiVersion: v1
metadata:
  name: redis-primary
  namespace: test-project
  selfLink: /api/v1/namespaces/test-project/services/redis-primary
  uid: eb97842c-a352-4c1c-9b7b-f941398562c2
  resourceVersion: '8638265'
  creationTimestamp: '2020-11-09T09:24:31Z'
spec:
  ports:
    - name: redis-master
      protocol: TCP
      port: 6379
      targetPort: 6379
    - name: redis-sentinel
      protocol: TCP
      port: 26379
      targetPort: 26379
  selector:
    app: redis-primary
  clusterIP: 172.30.13.73
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
