kind: Service
apiVersion: v1
metadata:
  name: redis-secondary
spec:
  ports:
    - protocol: TCP
      port: 26379
      targetPort: 26379
  selector:
    app: redis-secondary
  type: ClusterIP
  sessionAffinity: None