kind: Service
apiVersion: v1
metadata:
  name: redis-primary
spec:
  ports:
    - name: redis-master
      protocol: TCP
      port: 6379
      targetPort: 6379
    - name: redis-sentinel
      protocol: TCP
      port: 26379
      targetPort: 26379
  selector:
    app: redis-primary
  type: ClusterIP
  sessionAffinity: None