FROM redis:6.0.6
EXPOSE 6379
COPY redis-sentinel.conf /usr/local/etc/redis/sentinel.conf
COPY start-sentinel.sh /usr/bin/start.sh
RUN chmod 777 /usr/local/etc/redis/sentinel.conf
CMD /usr/bin/start.sh